In [1]:
# boolean Indexing
import numpy as np

In [2]:
arr=np.arange(1,10)
arr=arr.reshape(3,3)
print(arr)
print(arr[arr>5])
print(arr[arr%2==0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]
[2 4 6 8]


In [3]:
arr2=np.arange(10,100,10)
arr2=arr2.reshape(3,3)
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
# Append
arr3=np.append(arr2,arr,axis=0)
print(arr3)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [5]:
# Append
arr4=np.append(arr,arr2,axis=1)
print(arr4)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


In [6]:
arr5= np.arange(25,29)
arr5=arr5.reshape(2,2)
print(arr5)

[[25 26]
 [27 28]]


In [7]:
# Insert
insertarray=np.insert(arr,1,arr2,axis=0)
print(insertarray)

[[ 1  2  3]
 [10 20 30]
 [40 50 60]
 [70 80 90]
 [ 4  5  6]
 [ 7  8  9]]


In [8]:
delarr=np.delete(insertarray,1,axis=0)
print(delarr)

[[ 1  2  3]
 [40 50 60]
 [70 80 90]
 [ 4  5  6]
 [ 7  8  9]]


In [9]:
#SAVE
np.savetxt("arraydata.txt",arr2,fmt='%.0f')

In [10]:
a1=np.loadtxt("arraydata.txt",dtype=np.int32)
print(a1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
#Skipping Rows
a1=a1=np.loadtxt("arraydata.txt",dtype=np.int32,skiprows=1)
print(a1)

[[40 50 60]
 [70 80 90]]


In [12]:
c1,c2,c3=np.loadtxt("arraydata.txt",dtype=np.int32,skiprows=1,unpack=True)
print(c1)
print(c2)
print(c3)

[40 70]
[50 80]
[60 90]


In [13]:
# Packing and unpacking
t=1,2,3,4
print(t)
a,b,c,d=t
print(a)
print(b)
print(c)
print(d)

(1, 2, 3, 4)
1
2
3
4


# Pandas


In [14]:
import pandas as pd

In [15]:
s1=pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [16]:
s1=pd.Series([10,20,30,40,50],index=[101,102,103,104,105])
print(s1)

101    10
102    20
103    30
104    40
105    50
dtype: int64


In [17]:
print(s1[103])
print(s1[2])
# Not on every cases you can access the value of index
# here it will confuse on the basis of inddex number and error and label it will give the output
# Numeric then on basis of labels 
#and alpha numeric then acess on the basis of indexing

30


KeyError: 2

In [ ]:
import pandas as pd
s2=pd.Series([10,20,30,40,50],index=[101,102,103,104,105])
print(s2)

In [ ]:
import pandas as pd
s2=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(s2)

In [ ]:
print(s2['c'])
print(s2[103])

In [ ]:
# LOC AND ILOC  Difference
print("Slicing 1",s1.iloc[0:3])


In [ ]:
# LOC AND ILOC  Difference
print("Slicing 1",s1.loc['a':'e'])

# Loc work on the labels


# Dict


In [ ]:
d1={'c1':[100,200,300],'c2':[400,500,600],'c3':[700,800,900]}
d1=pd.DataFrame(d1)
print(d1)

In [ ]:
d1={'c1':[100,200,300],'c2':[400,500,600],'c3':[700,800,900]}
d1=pd.DataFrame(d1,index=[2001,2002,2003],columns=['College1','College2','College3'])
print(d1)

# Dont add any columns  if we add then it will replace by nan
#If we add the we get the nan value

# Load irirs data set

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data=load_iris()
print(data)

In [ ]:
##data=pd.DataFrame(data=data['data'])
#data.head()

In [ ]:
d1=pd.DataFrame(data=data['data'],columns=data['feature_names'])
d1.head()

In [ ]:
data.keys()

In [ ]:
d1['Flower_Type']=data['target']
d1.head()

In [ ]:
d1['label']=d1.Flower_Type.replace(dict(enumerate(data.target_names)))
d1

In [ ]:
data.keys()

In [ ]:
e=enumerate(data.target_names)
for i in e:
    print(i)
    

In [ ]:
l1=[10,20,30,40,50]
e=enumerate(l1,start=50)
e

In [ ]:
for t in e:
    print(t)

In [ ]:
milk=pd.read_csv('C:\\Users\\Admin\\Data Science Skill Circlle Aayush\\monthly-milk-production-pounds-p.csv')

In [ ]:
milk.head()

In [ ]:
# Rename the columns
m=milk.rename(columns={'Monthly milk production: pounds per cow. Jan 62 ? Dec 75':'production'})

In [ ]:
m.head()

In [ ]:
# Date and Time
import datetime
m['Month']=datetime.datetime.now()
m.head()